#!/usr/bin/env bash	

WGET=$(which wget)	
TAR=$(which tar)	

for COMMAND in "${WGET}" "${TAR}"; do	
    if [[ -z "${COMMAND}" ]]; then	
        echo "${COMMAND} not installed"	
        exit 1	
    fi	
done	

LINK='https://data.services.jetbrains.com/products/download?platform=linux&code=TBA'	

TEMP_DIR=$(mktemp -d -q)	
TOOLBOX_TAR="${TEMP_DIR}/toolbox.tar.gz"	
${WGET} -cO "${TOOLBOX_TAR}" "${LINK}"	
tar -xf "${TOOLBOX_TAR}" -C "${TEMP_DIR}" --strip-components=1	
exec "${TEMP_DIR}/jetbrains-toolbox" &